main_app/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('songs/', views.song_index, name='song-index'),
    path('songs/<int:song_id>/', views.song_detail, name='song-detail'),
    path('songs/create/', views.SongCreate.as_view(), name='song-create'),
    path('songs/<int:pk>/update/', views.SongUpdate.as_view(), name='song-update'),
    path('songs/<int:pk>/delete/', views.SongDelete.as_view(), name='song-delete'),
    path('songs/<int:song_id>/add-artist/', views.add_artist, name='add-artist'),
    path('accounts/signup/', views.signup, name='signup'),
]

musictracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Song(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    date = models.DateField()
    length = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('song-detail', kwargs={'song_id': self.id})
    
class Artist(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

main_app/forms.py
from django import forms
from .models import Artist

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['name', 'age']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Song
from .forms import ArtistForm
from django.contrib.auth.views import LoginView

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('song-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

def home(request):    
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def song_index(request):
    songs = Song.objects.filter(user=request.user)
    return render(request, 'songs/index.html', {'songs': songs})

@login_required
def song_detail(request, song_id):
    song = Song.objects.get(id=song_id)
    artist_form = ArtistForm()
    return render(request, 'songs/detail.html', {'song': song, 'artist_form': artist_form})

@login_required
def add_artist(request, song_id):
    form = ArtistForm(request.POST)
    if form.is_valid():
        new_artist = form.save(commit=False)
        new_artist.song_id = song_id
        new_artist.save()
    return redirect('song-detail', song_id=song_id)

class Home(LoginView):
    template_name = 'home.html'

class SongCreate(LoginRequiredMixin, CreateView):
    model = Song
    fields = ['name', 'genre', 'date', 'length']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class SongUpdate(LoginRequiredMixin, UpdateView):
    model = Song
    fields = ['name', 'genre', 'date', 'length']

class SongDelete(LoginRequiredMixin, DeleteView):
    model = Song
    success_url = '/songs/'

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Music Tracker</h1>
<hr />
<p class="page-content">
  A cool place to keep track of all of your favorite songs!
</p>

<input type=button value="Previous Page" onClick="javascript:history.go(-1);">

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Music Tracker</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">Home Page</a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'song-index' %}">All Songs</a></li>
            <li><a href="{% url 'song-create' %}">Add a Song</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id='logout-form' method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %} 
      {% endblock %}
    </main>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}

<div class="title">
  <h1>Welcome to the Music Tracker!</h1>
  <h2>One place to track all of your favorite songs!</h2>
</div>

<section class="logo-container">
  <div class="song-container">
    <img class="image-style" src="{% static 'images/music_note.jpeg' %}" alt="picture of a music score" />
  </div>
  <img src="" alt="" />
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}" />
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/song_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Song?</h1>
  <img src="" alt="" />
</div>

<h2>Are you sure you want to delete {{ song.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'song-detail' song.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/song_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  {% if object %}
    <h1>Edit {{ object.name }}</h1>
  {% else %}
    <h1>Add a Song</h1>
  {% endif %}
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

<input type=button value="Previous Page" onClick="javascript:history.go(-1);">

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <!-- <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" /> -->
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/songs/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/songs/song-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="song-container">
  <div class="song-img">
    <img src="" alt="" />
  </div>
  <div class="song-details">
    <h1>{{ song.name }}</h1>
      <h2>Genre: {{ song.genre }}</h2>
      <h2>Published on {{ song.date }} and is {{song.length}} minutes long.</h2>

    <div class="song-actions">
        <a href="{% url 'song-update' song.id %}" class="btn warn">Edit</a>
        <a href="{% url 'song-delete' song.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>

<section class="artist-container">
  <div class="title">
    <h2>Artist</h2>
  </div>
  <h3>Add an Artist</h3>
  <form action="{% url 'add-artist' song.id %}" method="post" class="content" autocomplete="off">
    {% csrf_token %}
    {{ artist_form.as_p }}
    <button type="submit" class="btn submit">Add Artist</button>
  </form>
  <h3>Artists</h3>
  {% if song.artist_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
        </tr>
      </thead>
      <tbody>
        {% for artist in song.artist_set.all %}
          <tr>
            <td>{{artist.name}}</td>
            <td>{{artist.age}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="content">
      <p>⚠️ {{song.name}} has not been assigned an artist!</p>
    </div>
  {% endif %}
</section>

<input type=button value="Previous Page" onClick="javascript:history.go(-1);">

{% endblock %}

main_app/templates/songs/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href=""/>
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>Song List</h1>
  <img src="" alt="" />
</section>

<section class="card-container">
  {% for song in songs %}
    <div class="card">
      <a href="{% url 'song-detail' song.id %}">
        <div class="card-content">
          <div class="card-img-container">
            <img
              src="{% static 'images/play_button.jpeg' %}"
              alt="headphones"
            />
          </div>
          <h2 class="card-title">{{ song.name }}</h2>
        </div>
      </a>
      <div class="card-info">
        <h3>{{ song.genre }} song</h3>
        <h3>{{ song.length }} minutes long</h4>
        <h3>published on {{ song.date }}</h3>
      </div>
    </div>
  {% endfor %}
</section>

<input type=button value="Previous Page" onClick="javascript:history.go(-1);">

{% endblock %}